config/routes.rb
Rails.application.routes.draw do

resources :events
  
  get 'events/new', to: 'events#create'

  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'
  get 'users/index'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  post 'signup', to: 'users#create'
  get 'signup', to: 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, :class_name => "User"
	has_many :attendees, :class_name => "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, :foreign_key => "creator_id", :class_name => "Event"
  has_many :attended_events, :through => :invitations, :class_name => "Event"
  has_many :invitations, :foreign_key => "attendee_id"
  validates :email, uniqueness: true, presence: true
  validates :password_digest, presence: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def must_login
    if !logged_in?
      flash[:danger] = "GO TE CONNECTER !! "
      redirect_to login_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
  	@events = Event.all
  end

  def new
  	@event = Event.new
  end


  def show
  	@event = Event.find(params[:id])
  end


  def create
  	   @event = Event.new(event_params)
   	   @event.creator = current_user
       @event.save
       p "erreurs :"
       @event.errors.each {|e| p e}
       p "fin des erreurs"
       flash[:success] = "évènement créé !"
  end

  def destroy
  	@event = Event.find(params[:id])
  	@event.destroy
 
  	redirect_to events_path
  end


	private
  def event_params
    params.permit(:title, :description, :date, :place)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, ready for some awesomness ?"

      redirect_to root_path
    else
      flash.now[:danger] = "It seems like you're not one of us ?"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "Hope to see you soon !"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :must_login, only: [:show]


  def create
     @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You are logged in !"
      redirect_to root_path
    else
      flash.now[:danger] = "Something went wrong try again"
      render 'new'
    end
  end

  def index
  end

  def new
  end

  def edit
   @user = User.find(params[:id])
   if @user.id != current_user.id 
    flash[:danger] = "No new friends !"
    redirect_to root_path
   end
  end

  def update
    @user = User.find(params[:id])
    if @user.id == current_user.id && @user.update(user_params)
      flash[:success] = "You edited your profile !"
      redirect_to show_profile_path
    else
      flash.now[:danger] = "Something went wrong try again"
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.id == current_user.id
      session[:user_id] = nil
      @user.destroy
      flash[:success] = "You deleted your account !"
      redirect_to root_path
    end
  end

  private

  def user_params
    params.permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/new.html.erb
<h1>Wants to plan a great event ?</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3 well">
        <%= form_tag '/events' do  %>
         <div class="form-group">
          <div class="form-group">
            <label for="title">Title</label>
            <%= text_field_tag :title, nil, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label for="description">Description</label>
            <%= text_field_tag :description, nil, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label for="date">Date</label>
            <%= date_field_tag :date, nil, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label for="place">Place</label>
            <%= text_field_tag :place, nil, class: 'form-control' %>
          </div>
          <%= submit_tag 'Create event', class: 'btn btn-primary btn-block' %>
        
        <% end %>
      </div>
    </div>
</div>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <div class="navbar-header">
        </div>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', root_path, class: 'nav-link' %></li>
            <% if !logged_in? %>
              <li><%= link_to 'Log in', login_path, class: 'nav-link' %></li>
              <li><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
            <% else %>
              <li><%= link_to 'Log out', logout_path, class: 'nav-link',
                  method: :delete %></li>
             <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
         <% flash.each do |type, message| %>
           <div class="alert alert-<%= type %>"><%= message %>
           </div>
         <% end %>


    <%= yield %>

  </body>
</html>

app/views/users/index.html.erb
<div class="jumbotron" >
<h1> Great Events For Great People. </h1> 
<br> </br>
<p style="font-size:16px">
<h3>Do you feel left behind ? Join us, we'll be pleased to meet you !</h3> 
<br></br>
<i> "Few are those who see with their own eyes and feel with their own hearts."</i> Albert Einstein
</p>
</div> 

app/views/users/new.html.erb
<h1> The greatest event for great people. You should sign up !</h1> 
<div class="row">
    <div class="col-md-6 col-md-offset-3 well">
        <%= form_tag '/signup' do  %>
         <div class="form-group">
          <div class="form-group">
            <label for="name">Name</label>
            <%= text_field_tag :name, nil, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label for="email">Email address</label>
            <%= text_field_tag :email, nil, class: 'form-control' %>
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <%= password_field_tag :password, nil, class: 'form-control' %>
          </div>
          <%= submit_tag 'Signup', class: 'btn btn-primary btn-block' %>
        
        <% end %>
      </div>

app/views/users/show.html.erb
<h1> La réponse est .... <h1>
  <p>42 !!!!!</p>